<a href="https://colab.research.google.com/github/BhumikaMahajan87/ML_assignments/blob/main/ML_assign_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#assignment 1
#question 1

import numpy as np
arr= np.array([1,2,3,4,5])
reversed_arr= arr[::-1]     #array[start:stop:step]

print("original array: ",arr)
print("reversed array: ",reversed_arr)


original array:  [1 2 3 4 5]
reversed array:  [5 4 3 2 1]


In [ ]:
#question 2

import numpy as np
arr= np.array([[1,2,3],[2,4,5],[1,2,3]])
flattened_arr= arr.flatten()

print("original array: ",arr)
print("flattened array: ",flattened_arr)



original array:  [[1 2 3]
 [2 4 5]
 [1 2 3]]
flattened array:  [1 2 3 2 4 5 1 2 3]


In [ ]:
#question 3 : comparing two numpy arrays

import numpy as np
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[1,2],[3,4]])
equal_or_not= np.array_equal(arr1,arr2)

print("if arr1 and arr2 are equal or not : ",equal_or_not)

if arr1 and arr2 are equal or not :  True


In [ ]:
#question 4 : most frequent value and indices

import numpy as np

x = np.array([1,2,3,4,5,1,2,1,1,1])
most_freq_x =np.argmax(np.bincount(x))
indicies_x=np.where(x==most_freq_x)[0]
print("most frequent value in x : ",most_freq_x)
print("indicies of most frequent value in x: ",indicies_x)

y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
most_freq_y =np.argmax(np.bincount(y))
indicies_y=np.where(y==most_freq_y)[0]
print("most frequent value in y : ",most_freq_y)
print("indicies of most frequent value in y: ",indicies_y)

most frequent value in x :  1
indicies of most frequent value in x:  [0 5 7 8 9]
most frequent value in y :  1
indicies of most frequent value in y:  [0 1 2]


In [ ]:
#question 5 : sum of all elements

import numpy as np
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')

sum_all_elements= np.sum(gfg)
sum_row_wise= np.sum(gfg,axis=1)
sum_col_wise= np.sum(gfg,axis=0)

print("Sum of all elements: ",sum_all_elements)
print("sum of all elements row wise: ",sum_row_wise)
print("sum of all elements column wise: ",sum_col_wise)

Sum of all elements:  45
sum of all elements row wise:  [[14]
 [16]
 [15]]
sum of all elements column wise:  [[20  9 16]]


In [ ]:
#question 6 : matrix operations

import numpy as np
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])

sum_of_diagonal= np.trace(n_array)
print("sum_of_diagonal elements:\n",sum_of_diagonal)

eigenvalues,eigenvectors=np.linalg.eig(n_array)
print("eigen values of matrix:\n",eigenvalues)
print("eigen vector of matrix:\n",eigenvectors)

inverse_matrix=np.linalg.inv(n_array)
print("inverse of matrix:\n",inverse_matrix)

determinant= np.linalg.det(n_array)
print("determinant of matrix: ",determinant)


sum_of_diagonal elements:
 176
eigen values of matrix:
 [98.16835147 28.097044   49.73460452]
eigen vector of matrix:
 [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
inverse of matrix:
 [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
determinant of matrix:  137180.0000000001


In [ ]:
#question 7 : mupliplication and covariance

import numpy as np
p1= np.array([[1,2],[2,3]])
q1= np.array([[4,5],[6,7]])

product_1= np.dot(p1,q1)
print("matrix multplication of 1 : \n",product_1)

p1_flatten=p1.flatten()
q1_flatten=q1.flatten()
covariance_1= np.cov(p1_flatten,q1_flatten)[0,1]     #covariance is obtained from [0,1] element of matrix
print("covariance between matrices of 1: ",covariance_1)


p2= np.array([[1, 2], [2, 3], [4, 5]])
q2=np.array([[4, 5, 1], [6, 7, 2]])

product_2= np.dot(p2,q2)
print("matrix multplication of 2 : \n",product_2)

p2_flatten=p2.flatten()
q2_flatten=q2.flatten()
covariance_2= np.cov(p2_flatten,q2_flatten)[0,1]
print("covariance between matrices of 2: ",covariance_2)

matrix multplication of 1 : 
 [[16 19]
 [26 31]]
covariance between matrices of 1:  1.0
matrix multplication of 2 : 
 [[16 19  5]
 [26 31  8]
 [46 55 14]]
covariance between matrices of 2:  0.23333333333333336


In [ ]:
#question 8 : cartesian product
import numpy as np
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])

inner_product=np.inner(x,y)
print("inner product: \n",inner_product)

outer_product=np.outer(x,y)
print("outer product: \n",outer_product)

x_flat= x.flatten()
y_flat= y.flatten()
x1,y1= np.meshgrid(x_flat,y_flat)
cartesian_product= np.array([x1.ravel(),y1.ravel()]).T
print("cartesian product: ",cartesian_product)



inner product: 
 [[17 52]
 [13 62]]
outer product: 
 [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
cartesian product:  [[ 2  1]
 [ 3  1]
 [ 4  1]
 [ 3  1]
 [ 2  1]
 [ 9  1]
 [ 2  5]
 [ 3  5]
 [ 4  5]
 [ 3  5]
 [ 2  5]
 [ 9  5]
 [ 2  0]
 [ 3  0]
 [ 4  0]
 [ 3  0]
 [ 2  0]
 [ 9  0]
 [ 2  5]
 [ 3  5]
 [ 4  5]
 [ 3  5]
 [ 2  5]
 [ 9  5]
 [ 2 10]
 [ 3 10]
 [ 4 10]
 [ 3 10]
 [ 2 10]
 [ 9 10]
 [ 2  3]
 [ 3  3]
 [ 4  3]
 [ 3  3]
 [ 2  3]
 [ 9  3]]


In [ ]:
import numpy as np

array = np.array([[1, -2, 3],[-4, 5, -6]])

absolute_array=np.abs(array)
print("element-wise absolute value: \n",absolute_array)

flattened_array= array.flatten()
percentile_flattened= np.percentile(flattened_array,[25,50,75])
percentile_column= np.percentile(array,[25,50,75],axis=0)
percentile_row= np.percentile(array,[25,50,75],axis=1)

print("percentile of flattened array(25,50,75): \n",percentile_flattened)
print("percentile of each column(25,50,75): \n",percentile_column)
print("percentile of each row(25,50,75): \n",percentile_row)

mean_flattened=np.mean(flattened_array)
median_flattened=np.median(flattened_array)
std_flattened=np.std(flattened_array)

mean_column=np.mean(array,axis=0)
median_column=np.median(array,axis=0)
std_column=np.std(array,axis=0)

mean_rows=np.mean(array,axis=1)
median_rows=np.median(array,axis=1)
std_rows=np.std(array,axis=1)

print("Mean ,median and standard deviation of flattened array : ")
print("mean: ",mean_flattened)
print("median: ",median_flattened)
print("standard deviation: ",std_flattened)

print("Mean ,median and standard deviation of of each column : ")
print("mean: ",mean_column)
print("median: ",median_column)
print("standard deviation: ",std_column)

print("Mean ,median and standard deviation of each row : ")
print("mean: ",mean_rows)
print("median: ",median_rows)
print("standard deviation: ",std_rows)




element-wise absolute value: 
 [[1 2 3]
 [4 5 6]]
percentile of flattened array(25,50,75): 
 [-3.5 -0.5  2.5]
percentile of each column(25,50,75): 
 [[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
percentile of each row(25,50,75): 
 [[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]
Mean ,median and standard deviation of flattened array : 
mean:  -0.5
median:  -0.5
standard deviation:  3.8622100754188224
Mean ,median and standard deviation of of each column : 
mean:  [-1.5  1.5 -1.5]
median:  [-1.5  1.5 -1.5]
standard deviation:  [2.5 3.5 4.5]
Mean ,median and standard deviation of each row : 
mean:  [ 0.66666667 -1.66666667]
median:  [ 1. -4.]
standard deviation:  [2.05480467 4.78423336]


In [ ]:
import numpy as np

a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0])

floor_val=np.floor(a)
ceiling_val=np.ceil(a)
truncated_val=np.trunc(a)
rounded_val=np.round(a)

print("floor value: \n",floor_val)
print("ceiling value: \n",ceiling_val)
print("truncated value: \n",truncated_val)
print("rounded value: \n",rounded_val)


floor value: 
 [-2. -2. -1.  0.  1.  1.  3.]
ceiling value: 
 [-1. -1. -0.  1.  2.  2.  3.]
truncated value: 
 [-1. -1. -0.  0.  1.  1.  3.]
rounded value: 
 [-2. -2. -0.  0.  2.  2.  3.]


In [ ]:
import numpy as np

array=np.array([10,52,62,16,16,54,453])

sorted_arr=np.sort(array)
indicies_sorted_arr= np.argsort(array)

smallest_elements= np.partition(array,4)[:4]
smallest_elements_sorted= np.sort(smallest_elements)

largest_elements= np.partition(array,-5)[-5:]
largest_elements_sorted=np.sort(largest_elements)

print("sorted array: ",sorted_arr)
print("indicies of sorted array: ",indicies_sorted_arr)
print("4 smallest element: \n",smallest_elements_sorted)
print("5 largest elements: \n",largest_elements_sorted)




sorted array:  [ 10  16  16  52  54  62 453]
indicies of sorted array:  [0 3 4 1 5 2 6]
4 smallest element: 
 [10 16 16 52]
5 largest elements: 
 [ 16  52  54  62 453]


In [ ]:
import numpy as np

array= np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
integer_elements= array[array==array.astype(int)]
float_elements= array[array!= array.astype(int)]

print("integer elements: ",integer_elements)
print("float elements: ",float_elements)


integer elements:  [1. 2. 3. 2.]
float elements:  [1.2 2.2]
